### ISSUE TITLE
Add user acceptance tests for email delivery and content

### ISSUE THREAD

**Issue by samtuke** [phpList/phplist3#412]
Add Behat-based user acceptance tests to check the following:

- Campaigns generate and send emails when queued
- Emails are received by a real inbox
- Textual email content within received emails is correct (matches what was set in the campaign composer)

**Comment by kilip** [comment]
Hello All,

Finally I can make a pull request for this issue in #427. Here's some notes about implementation:

1.  SMTP implemented by using smtp sink. Here's how I setup my dev environment:
```sh
$ cd /path/to/phplist
$ sudo apt-get install postfix
# we don't need postfix
$ sudo service postfix stop

# smtp-sink always write in current directory,
# so we need to cd first before start smtp-sink
$ mkdir -p build/mails
$ cd build/mails
$ smtp-sink -d "%d.%H.%M.%S" localhost:2500 1000 &
```
- You need to setup your ```config.php``` file to use this smtp-sink:
```php
define('PHPMAILERHOST', 'localhost');
define('PHPMAILERPORT',2500);
define('PHPMAILER_SECURE',false);
define('TEST', 0);
```

2. New Context added, so your ```behat.yml``` file need to be reconfigured:
```yaml
default:
    suites:
        default:
            contexts:
                - MailContext:
                    mail_dir: %paths.base%/build/mails
                - SubscriberContext
                - UserContext
```

**Comment by kilip** [comment]
Hello All,

Finally I can make a pull request for this issue in #427. Here's some notes about implementation:

1.  SMTP implemented by using smtp sink. Here's how I setup my dev environment:
```sh
$ cd /path/to/phplist
$ sudo apt-get install postfix
# we don't need postfix
$ sudo service postfix stop

# smtp-sink always write in current directory,
# so we need to cd first before start smtp-sink
$ mkdir -p build/mails
$ cd build/mails
$ smtp-sink -d "%d.%H.%M.%S" localhost:2500 1000 &
```
- You need to setup your ```config.php``` file to use this smtp-sink:
```php
define('PHPMAILERHOST', 'localhost');
define('PHPMAILERPORT',2500);
define('PHPMAILER_SECURE',false);
define('TEST', 0);
```

2. New Context added, so your ```behat.yml``` file need to be reconfigured:
```yaml
default:
    suites:
        default:
            contexts:
                - MailContext:
                    mail_dir: %paths.base%/build/mails
                - SubscriberContext
                - UserContext
```
To create a new scenario using this context, you need to add ```@emptySentMail``` so MailContext can empty ```build/mails``` directory before scenario tests started:
```gherkin
# sample scenario using new context definition
# ref file in: tests/features/smtp.feature
@emptySentMail @javascript
    Scenario: Sending campaign with list subscribers
        Given I have logged in as an administrator
        And I have "smtp" list with the following subscribers:
            """
            test1@phplist.dev
            test2@phplist.dev
            test3@phplist.dev
            """
        And I should have email sent from "From Me"
        And I should have email sent from address "me@mydomain.com"
        And I should have email sent to address "test1@phplist.dev"
        And I should have email sent to address "test2@phplist.dev"
        And I should have email sent to address "test3@phplist.dev"
        And I should have email sent contains "This is the Content of the SMTP Campaign"
        And I should have email sent contains "This is the Footer of the campaign"
```
